---
title: "Quantifying The Effect of Pitching Metrics "
author: "Max Brown"
date: "May 20, 2022"
output: 
  pdf_document: 
    fig_height: 3
    fig_width: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, 
                      warning = F, 
                      message = F)
```


```{r load-packages}
# load packages
library(tidyverse)
library(knitr)
library(lme4)
library(broom.mixed)
library(skimr)
library(readr)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(knitr)
library(lme4)
library(broom.mixed)
library(skimr)
library(readr)
library(ggplot2)
library(dplyr)
```



```{r}
lefty_ninth <- read_csv("lefty_ninth.csv")
righty_ninth <- read_csv("righty_ninth.csv")
```




```{r inch-switch}
lefty_ninth <- lefty_ninth %>% mutate(hor_break = (pfx_x*12), 
                                      ind_vert_break = (pfx_z*12))
righty_ninth <- righty_ninth %>% mutate(hor_break = (pfx_x*12), 
                                      ind_vert_break = (pfx_z*12))
```


```{r pitch-breakup}
rh_fastball <- righty_ninth %>% filter(pitch_type == c("FF", "FA", "SI", "FC"))
rh_breakingball <- righty_ninth %>% filter(pitch_type == c("KC", "SL", "CU","CS"))
rh_changeup <- righty_ninth %>% filter(pitch_type == c("CH", "FS"))

lh_fastball <- lefty_ninth %>% filter(pitch_type == c("FF", "FA", "SI", "FC"))
lh_breakingball <- lefty_ninth %>% filter(pitch_type == c("KC", "SL", "CU","CS"))
lh_changeup <- lefty_ninth %>% filter(pitch_type == c("CH", "FS"))
```





## General EDA 

```{r expected-batting-average-by-speed/angle}
ggplot(data = subset(righty_ninth, !is.na(estimated_ba_using_speedangle)), 
       mapping = aes(x=launch_speed, y=launch_angle, 
                     color = estimated_ba_using_speedangle)) + 
  geom_point() + labs(title = "Right-Handed Speed/Angle Breakdown", 
                      x = "Exit Velocity (mph)", 
                      y = "Launch Angle (degrees)") 


```

```{r}
ggplot(data = subset(lefty_ninth, !is.na(estimated_ba_using_speedangle)), 
       mapping = aes(x=launch_speed, y=launch_angle, 
                     color = estimated_ba_using_speedangle)) + 
  geom_point() + labs(title = "Left-Handed Speed/Angle Breakdown", 
                      x = "Exit Velocity (mph)", 
                      y = "Launch Angle (degrees)") 
```

```{r}
righty_ninth <- righty_ninth %>% 
  mutate(inplay_out = ifelse(events == c("double_play", "field_out", 
                                         "fielders_choice_out", "force_out", 
                                         "grounded_into_double_play", 
                                         "other_out", "sac_fly",
                                         "sac_fly_double_play"), "1", "0"))

r_in_play_df <- righty_ninth %>% filter(description == "hit_into_play")

ggplot(data = r_in_play_df, mapping = aes(x=release_speed, y=launch_speed, 
                                color = inplay_out)) + 
  geom_point() + labs(title = "No Relationship For Release Speed and Launch Speed/Out Made", 
                      x = "Release Speed of Pitch", 
                      y = "Exit Speed of Contact", 
                      color = "Out Recorded") 


```




### Fastball EDA

```{r rh-fastball-groups}
ggplot(data = rh_fastball, mapping = aes(x=hor_break, y=ind_vert_break, 
                                color = pitch_name)) + 
  geom_point() + labs(title = "Right-Handed Fastball Breakdown", 
                      x = "Horizontal Break (in)", 
                      y = "Induced Vertical Break (in)") 

```

```{r lh-fastball-groups}
ggplot(data = lh_fastball, mapping = aes(x=hor_break, y=ind_vert_break, 
                                color = pitch_name)) + 
  geom_point() + labs(title = "Left-Handed Fastball Breakdown", 
                      x = "Horizontal Break (in)", 
                      y = "Induced Vertical Break (in)") 
```

```{r}
rhf_stats <- rh_fastball %>% drop_na(release_speed, release_spin_rate, hor_break, 
                        ind_vert_break, spin_axis) %>% group_by(pitch_name) %>% 
  summarize(release_speed = mean(release_speed), 
            release_spin = mean(release_spin_rate),
            hor_break = mean(hor_break), 
            vert_break = mean(ind_vert_break), 
            tilt = mean(spin_axis)) 

kable(rhf_stats, caption = "Average RH Fastball Type Metrics", digits = 2)
```


```{r}
lhf_stats <- lh_fastball %>% drop_na(release_speed, release_spin_rate, hor_break, 
                        ind_vert_break, spin_axis) %>% group_by(pitch_name) %>% 
  summarize(release_speed = mean(release_speed), 
            release_spin = mean(release_spin_rate),
            hor_break = mean(hor_break), 
            vert_break = mean(ind_vert_break), 
            tilt = mean(spin_axis))

kable(lhf_stats, caption = "Average LH Fastball Type Metrics", digits = 2)
```



### EDA Breaking Balls 

```{r}
ggplot(data = rh_breakingball, mapping = aes(x=hor_break, y=ind_vert_break, 
                                color = pitch_name)) + 
  geom_point() + labs(title = "Right-Handed Breaking Ball Breakdown", 
                      x = "Horizontal Break (in)", 
                      y = "Induced Vertical Break (in)") 
```

```{r}
ggplot(data = lh_breakingball, mapping = aes(x=hor_break, y=ind_vert_break, 
                                color = pitch_name)) + 
  geom_point() + labs(title = "Left-Handed Breaking Ball Breakdown", 
                      x = "Horizontal Break (in)", 
                      y = "Induced Vertical Break (in)") 
```



```{r}
rhb_stats <- rh_breakingball %>% drop_na(release_speed, release_spin_rate, hor_break, 
                        ind_vert_break, spin_axis) %>% group_by(pitch_name) %>% 
  summarize(release_speed = mean(release_speed), 
            release_spin = mean(release_spin_rate),
            hor_break = mean(hor_break), 
            vert_break = mean(ind_vert_break), 
            tilt = mean(spin_axis))
kable(rhb_stats, caption = "Average RH Breaking Ball Type Metrics", digits = 2)
```

```{r}
lhb_stats <- lh_breakingball %>% drop_na(release_speed, release_spin_rate, hor_break, 
                        ind_vert_break, spin_axis) %>% group_by(pitch_name) %>% 
  summarize(release_speed = mean(release_speed), 
            release_spin = mean(release_spin_rate),
            hor_break = mean(hor_break), 
            vert_break = mean(ind_vert_break), 
            tilt = mean(spin_axis))

kable(lhb_stats, caption = "Average LH Breaking Ball Type Metrics", digits = 2)
```


### EDA Change Ups

```{r}
ggplot(data = rh_changeup, mapping = aes(x=hor_break, y=ind_vert_break, 
                                color = pitch_name)) + 
  geom_point() + labs(title = "Right-Handed Change Up Breakdown", 
                      x = "Horizontal Break (in)", 
                      y = "Induced Vertical Break (in)") 
```

```{r}
ggplot(data = lh_changeup, mapping = aes(x=hor_break, y=ind_vert_break, 
                                color = pitch_name)) + 
  geom_point() + labs(title = "Left-Handed Change Up Breakdown", 
                      x = "Horizontal Break (in)", 
                      y = "Induced Vertical Break (in)") 
```



```{r}
rhc_stats <- rh_changeup %>% drop_na(release_speed, release_spin_rate, hor_break, 
                        ind_vert_break, spin_axis) %>% group_by(pitch_name) %>% 
  summarize(release_speed = mean(release_speed), 
            release_spin = mean(release_spin_rate),
            hor_break = mean(hor_break), 
            vert_break = mean(ind_vert_break), 
            tilt = mean(spin_axis))

kable(rhc_stats, caption = "Average RH ChangeUp Type Metrics", digits = 2)
```

```{r}
lhc_stats <- lh_changeup %>% drop_na(release_speed, release_spin_rate, hor_break, 
                        ind_vert_break, spin_axis) %>% group_by(pitch_name) %>% 
  summarize(release_speed = mean(release_speed), 
            release_spin = mean(release_spin_rate),
            hor_break = mean(hor_break), 
            vert_break = mean(ind_vert_break), 
            tilt = mean(spin_axis))

kable(lhc_stats, caption = "Average LH Change Up Type Metrics", digits = 2)
```



## Methodology 

```{r}
righty_ninth <- subset(righty_ninth, select = -inplay_out )
all_rows <- rbind(righty_ninth, lefty_ninth)
```


```{r}
inplay_avg_benchmark <- all_rows %>% filter(description == "hit_into_play") %>% 
  drop_na(estimated_ba_using_speedangle) %>%
  summarise(mean_estimated_ba = mean(estimated_ba_using_speedangle))

inplay_avg_benchmark <- inplay_avg_benchmark$mean_estimated_ba
```


```{r}
pitcher_ideal_creation <- function(dataset) {
  dataset <- dataset %>% mutate(pitcher_ideal = if_else(description == "called_strike" | description == "foul"| description == "foul_bunt"| description == "foul_tip"| description == "missed_bunt"| description == "swinging_strike"| description == "swinging_strike_blocked" | estimated_ba_using_speedangle <= inplay_avg_benchmark , 1, 0))
  dataset <- dataset %>% mutate_at(vars("pitcher_ideal"), ~replace_na(.,0))
 return(dataset)
}

rh_fastball <- pitcher_ideal_creation(rh_fastball)
lh_fastball <- pitcher_ideal_creation(lh_fastball) 
rh_changeup <- pitcher_ideal_creation(rh_changeup) 
lh_changeup <- pitcher_ideal_creation(lh_changeup) 
rh_breakingball <- pitcher_ideal_creation(rh_breakingball)
lh_breakingball <- pitcher_ideal_creation(lh_breakingball)
```


### Creating Breaking Ball Models 

#### Right-Hand

```{r}
rh_breakingball <- rh_breakingball %>% mutate(mean_centered_speed = mean(release_speed) - release_speed)
rh_bb_model <- glm(pitcher_ideal ~ mean_centered_speed + 
                  hor_break + ind_vert_break, 
                data = rh_breakingball)

tidy(rh_bb_model) %>% kable(digits = 3)
```

#### Left-Hand 

```{r}
lh_breakingball <- lh_breakingball %>% mutate(mean_centered_speed = mean(release_speed) - release_speed)
lh_bb_model <- glm(pitcher_ideal ~ mean_centered_speed + 
                  hor_break + ind_vert_break, 
                data = lh_breakingball)

tidy(lh_bb_model) %>% kable(digits = 3)
```






## Appendix 

```{r}
right_names = righty_ninth %>% group_by(player_name) %>%  .$player_name
left_names = lefty_ninth %>% group_by(player_name) %>%  .$player_name
set.seed(3)

# get sample of 12 pitchers
sample_righties <- sample(right_names, 12)
sample_lefties <- sample(left_names, 12)

# get data for those schools
sample_data_r <- rh_fastball %>%
  filter(player_name %in% sample_righties)

sample_data_l <- lh_fastball %>% 
  filter(player_name %in% sample_lefties)

ggplot(data = sample_data_r, mapping = aes(x=release_extension, y=release_speed, 
                                color = pitch_name)) + facet_wrap(~player_name) +
  geom_point() + 
  labs(title = "Inconclusive Evidence of Righty Extension/Speed Relationship", 
       x = "Release Extension (Feet)", 
       y = "Release Speed (MPH)")



```


```{r}
ggplot(data = sample_data_l, mapping = aes(x=release_extension, y=release_speed, 
                                color = pitch_name)) + facet_wrap(~player_name) +
  geom_point() + 
  labs(title = "Inconclusive Evidence of Lefty Extension/Speed Relationship", 
       x = "Release Extension (Feet)", 
       y = "Release Speed (MPH)")
```
